# Generated by Django 5.2 on 2026-09-23 20:29

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_invitation'),
        ('crm', '0004_interaction_notification_task_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('provider', models.CharField(choices=[('kavenegar', 'کاوه\u200cنگار'), ('melipayamak', 'ملی\u200cپیامک'), ('console', 'کنسول (توسعه)')], default='console', max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('api_key', apps.core.fields.EncryptedCharField(blank=True, help_text='رمزنگاری\u200cشده در پایگاه داده', verbose_name='کلید API / نام کاربری')),
                ('api_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='رمزنگاری\u200cشده در پایگاه داده', verbose_name='رمز عبور / secret')),
                ('sender_line', models.CharField(blank=True, help_text='شماره فرستنده (خدماتی یا تبلیغاتی)', max_length=20, verbose_name='شماره خط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک آژانس',
                'verbose_name_plural': 'تنظیمات پیامک آژانس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('body', models.TextField(help_text='متغیرهای مجاز: {نام}, {نام_آژانس}, {تلفن_آژانس}, {کد_فایل}, {نوع_ملک}, {محله}', verbose_name='متن قالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
                'ordering': ['name'],
                'unique_together': {('agency', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('recipient_masked', models.CharField(max_length=10, verbose_name='گیرنده (آخر ۴ رقم)')),
                ('body', models.TextField(verbose_name='متن پیامک')),
                ('state', models.CharField(choices=[('queued', 'صف'), ('sent', 'ارسال\u200cشده'), ('delivered', 'تحویل\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='queued', max_length=20, verbose_name='وضعیت')),
                ('provider', models.CharField(blank=True, choices=[('kavenegar', 'کاوه\u200cنگار'), ('melipayamak', 'ملی\u200cپیامک'), ('console', 'کنسول (توسعه)')], max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه پیامک نزد ارائه\u200cدهنده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شکست')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل شکست')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هزینه')),
                ('segment_count', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد بخش')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='crm.contact', verbose_name='مخاطب')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.smstemplate', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', 'state'], name='messaging_s_agency__77eb76_idx'), models.Index(fields=['agency', 'created_at'], name='messaging_s_agency__5f67eb_idx'), models.Index(fields=['contact', 'created_at'], name='messaging_s_contact_69ebbc_idx')],
            },
        ),
    ]
