# Generated by Django 5.2 on 2026-09-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_invitation'),
        ('crm', '0004_interaction_notification_task_visit'),
        ('listings', '0005_import_job'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySMSPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('auto_send_exact', models.BooleanField(default=True, help_text='برای تطبیق\u200cهای با امتیاز ≥ score_threshold خودکار پیامک بفرست', verbose_name='ارسال خودکار برای تطبیق دقیق')),
                ('auto_send_strong', models.BooleanField(default=True, help_text='برای تطبیق\u200cهای با امتیاز ≥ 50 خودکار پیامک بفرست', verbose_name='ارسال خودکار برای تطبیق قوی')),
                ('score_threshold', models.PositiveSmallIntegerField(default=70, verbose_name='آستانه امتیاز ارسال خودکار')),
                ('quiet_start', models.PositiveSmallIntegerField(default=22, help_text='از این ساعت پیامک نفرست', verbose_name='ساعت شروع سکوت (0–23)')),
                ('quiet_end', models.PositiveSmallIntegerField(default=8, help_text='تا این ساعت پیامک نفرست', verbose_name='ساعت پایان سکوت (0–23)')),
                ('daily_cap', models.PositiveSmallIntegerField(default=2, verbose_name='سقف روزانه به ازای هر مخاطب')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('match_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.smstemplate', verbose_name='قالب پیامک تطبیق')),
            ],
            options={
                'verbose_name': 'سیاست پیامک آژانس',
                'verbose_name_plural': 'سیاست\u200cهای پیامک آژانس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MatchSMSSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sms_sent', to='agencies.agency')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sms_sent', to='listings.listing')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sms_sent', to='crm.request')),
                ('sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_sent', to='messaging.smsmessage')),
            ],
            options={
                'verbose_name': 'پیامک تطبیق ارسال\u200cشده',
                'verbose_name_plural': 'پیامک\u200cهای تطبیق ارسال\u200cشده',
                'indexes': [models.Index(fields=['agency', 'created_at'], name='messaging_m_agency__83e3a0_idx')],
                'unique_together': {('listing', 'request')},
            },
        ),
    ]
