# Generated by Django 5.2 on 2026-09-24 20:44

import django.db.models.deletion
from django.db import migrations, models

import apps.rendering.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_invitation'),
        ('listings', '0005_import_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('kind', models.CharField(choices=[('poster_pdf', 'پوستر PDF'), ('poster_png', 'پوستر PNG')], default='poster_pdf', max_length=20, verbose_name='نوع خروجی')),
                ('status', models.CharField(choices=[('pending', 'صف'), ('running', 'در حال رندر'), ('success', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('engine', models.CharField(blank=True, max_length=30, verbose_name='موتور رندر')),
                ('file', models.FileField(blank=True, max_length=500, upload_to=apps.rendering.models._render_output_path, verbose_name='فایل خروجی')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='پیغام خطا')),
                ('rendered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رندر')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='listings.listing', verbose_name='فایل ملک')),
            ],
            options={
                'verbose_name': 'job رندر',
                'verbose_name_plural': 'jobهای رندر',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', 'status'], name='rendering_r_agency__956d09_idx'), models.Index(fields=['listing', 'created_at'], name='rendering_r_listing_4f59f9_idx')],
            },
        ),
    ]
