# Generated by Django 5.2 on 2026-09-22 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_invitation'),
        ('core', '0001_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('view_phone', 'نمایش شماره'), ('login', 'ورود'), ('logout', 'خروج'), ('invite', 'دعوت عضو'), ('publish', 'انتشار'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='اقدام')),
                ('object_model', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='مدل')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='شناسه شیء')),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='نمایش شیء')),
                ('diff', models.JSONField(blank=True, null=True, verbose_name='تغییرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='مرورگر')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='اطلاعات اضافه')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='agencies.agency', verbose_name='آژانس')),
            ],
            options={
                'verbose_name': 'لاگ ممیزی',
                'verbose_name_plural': 'لاگ\u200cهای ممیزی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', 'action', '-created_at'], name='core_auditl_agency__c492be_idx'), models.Index(fields=['actor', '-created_at'], name='core_auditl_actor_i_502baf_idx'), models.Index(fields=['object_model', 'object_id'], name='core_auditl_object__40a247_idx')],
            },
        ),
    ]
