# Generated by Django 5.2 on 2026-09-22 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('phone', models.CharField(blank=True, help_text='اگر مشخص باشد — وگرنه هر کاربری با لینک می\u200cتواند استفاده کند', max_length=15, verbose_name='شماره موبایل مدعو')),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('agent', 'مشاور'), ('viewer', 'مشاهده\u200cگر')], default='agent', max_length=20, verbose_name='نقش پیشنهادی')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='توکن')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='انقضا')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='agencies.agency', verbose_name='آژانس')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL, verbose_name='استفاده\u200cکننده')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', 'is_used'], name='agencies_in_agency__3095d4_idx')],
            },
        ),
    ]
