# Generated by Django 5.2 on 2026-09-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_agency_member'),
        ('crm', '0002_rename_crm_request_agency_status_idx_crm_request_agency__b18a7e_idx_and_more'),
        ('listings', '0002_rename_listings_li_agency_status_idx_listings_li_agency__a8e908_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='۰ تا ۱۰۰ — هر چه بالاتر، تطبیق بهتر', verbose_name='امتیاز تطبیق')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='agencies.agency', verbose_name='آژانس')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='listings.listing', verbose_name='فایل ملک')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='crm.request', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'تطبیق',
                'verbose_name_plural': 'تطبیق\u200cها',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['agency', 'score'], name='matching_ma_agency__40b028_idx'), models.Index(fields=['request', 'score'], name='matching_ma_request_114f65_idx')],
                'unique_together': {('request', 'listing')},
            },
        ),
    ]
