# Generated by Django 5.2 on 2026-09-20 21:15

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_member'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_agency__a8e908_idx',
            old_name='listings_li_agency_status_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_agency__4c8b55_idx',
            old_name='listings_li_agency_deal_prop_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_agency__3b92e7_idx',
            old_name='listings_li_agency_city_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner_phone',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='شماره مالک'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='صفر = بدون اتاق', verbose_name='تعداد اتاق'),
        ),
    ]
