# Generated by Django 5.2 on 2026-09-22 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_invitation'),
        ('listings', '0002_rename_listings_li_agency_status_idx_listings_li_agency__a8e908_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون (مثلاً: elevator, parking, balcony)', max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'امکانات',
                'verbose_name_plural': 'امکانات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodAdjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'همجواری محله',
                'verbose_name_plural': 'همجواری\u200cهای محله',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='بالکن'),
        ),
        migrations.AddField(
            model_name='listing',
            name='land_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ زمین (m²)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.TextField(blank=True, verbose_name='موقعیت جغرافیایی (WKT)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='units_per_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='واحد در طبقه'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='توضیح'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='نام شهر')),
                ('province', models.CharField(db_index=True, max_length=100, verbose_name='استان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['province', 'name'],
                'unique_together': {('name', 'province')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.feature', verbose_name='امکانات'),
        ),
        migrations.CreateModel(
            name='ListingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('old_status', models.CharField(blank=True, choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('reserved', 'رزرو شده'), ('sold', 'فروخته / اجاره داده شده'), ('expired', 'منقضی')], max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('reserved', 'رزرو شده'), ('sold', 'فروخته / اجاره داده شده'), ('expired', 'منقضی')], max_length=20, verbose_name='وضعیت جدید')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='listings.listing', verbose_name='فایل ملک')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت',
                'verbose_name_plural': 'تاریخچه وضعیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='نام محله')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='فهرست JSON نام\u200cهای جایگزین برای جستجوی گفتاری و فازی', verbose_name='نام\u200cهای مترادف')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='listings.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'محله',
                'verbose_name_plural': 'محله\u200cها',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.neighborhood', verbose_name='محله'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['agency', 'neighborhood'], name='listings_li_agency__3f584b_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('floor__lte', models.F('total_floors')), ('floor__isnull', True), ('total_floors__isnull', True), _connector='OR'), name='listing_floor_lte_total_floors'),
        ),
        migrations.AddField(
            model_name='neighborhoodadjacency',
            name='from_neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacencies_from', to='listings.neighborhood', verbose_name='از محله'),
        ),
        migrations.AddField(
            model_name='neighborhoodadjacency',
            name='to_neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacencies_to', to='listings.neighborhood', verbose_name='به محله'),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('city', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='neighborhoodadjacency',
            unique_together={('from_neighborhood', 'to_neighborhood')},
        ),
    ]
