# Generated by Django 5.2 on 2026-09-22 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_feature_neighborhoodadjacency_listing_balcony_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('media_type', models.CharField(choices=[('photo', 'عکس'), ('video', 'ویدئو'), ('document', 'سند')], db_index=True, default='photo', max_length=10, verbose_name='نوع رسانه')),
                ('file', models.FileField(max_length=500, upload_to=apps.listings.models._media_upload_path, verbose_name='فایل')),
                ('thumbnail', models.FileField(blank=True, max_length=500, upload_to=apps.listings.models._thumb_upload_path, verbose_name='بندانگشتی')),
                ('webp', models.FileField(blank=True, max_length=500, upload_to=apps.listings.models._webp_upload_path, verbose_name='نسخه WebP')),
                ('is_private', models.BooleanField(default=False, help_text='اسناد خصوصی فقط با لینک امضاشده قابل دسترسند', verbose_name='سند خصوصی')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر شاخص')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('original_filename', models.CharField(blank=True, max_length=300, verbose_name='نام فایل اصلی')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پردازش'), ('processing', 'در حال پردازش'), ('ready', 'آماده'), ('error', 'خطا')], db_index=True, default='pending', max_length=15, verbose_name='وضعیت پردازش')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='پیغام خطا')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='listings.listing', verbose_name='فایل ملک')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='آپلود توسط')),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'رسانه\u200cها',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['listing', 'media_type', 'is_private'], name='media_listing_type_priv_idx')],
            },
        ),
    ]
