# Generated by Django 5.2 on 2026-09-22 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_invitation'),
        ('listings', '0004_media_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('uploaded_file', models.FileField(max_length=500, upload_to='imports/%Y/%m/', verbose_name='فایل آپلود\u200cشده')),
                ('original_filename', models.CharField(blank=True, max_length=300, verbose_name='نام فایل اصلی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('done', 'انجام شد'), ('error', 'خطا')], db_index=True, default='pending', max_length=15, verbose_name='وضعیت')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='کل ردیف\u200cها')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='ردیف\u200cهای موفق')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='ردیف\u200cهای خطا')),
                ('error_report', models.JSONField(blank=True, default=list, verbose_name='گزارش خطا')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد توسط')),
            ],
            options={
                'verbose_name': 'ایمپورت',
                'verbose_name_plural': 'ایمپورت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
