# Generated by Django 5.2 on 2026-09-20 21:15

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_member'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='request',
            new_name='crm_request_agency__b18a7e_idx',
            old_name='crm_request_agency_status_idx',
        ),
        migrations.RenameIndex(
            model_name='request',
            new_name='crm_request_agency__f1ad5a_idx',
            old_name='crm_request_agency_deal_idx',
        ),
        migrations.RenameIndex(
            model_name='request',
            new_name='crm_request_agency__69029f_idx',
            old_name='crm_request_agency_prio_idx',
        ),
        migrations.AlterField(
            model_name='request',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client_phone',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='شماره مراجعه\u200cکننده'),
        ),
    ]
