# Generated by Django 5.2 on 2026-09-22 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_invitation'),
        ('crm', '0002_rename_crm_request_agency_status_idx_crm_request_agency__b18a7e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('phone', apps.core.fields.EncryptedCharField(max_length=255, verbose_name='شماره')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='شماره (نرمال\u200cشده)')),
                ('label', models.CharField(choices=[('mobile', 'موبایل'), ('home', 'منزل'), ('work', 'محل کار'), ('other', 'سایر')], default='mobile', max_length=10, verbose_name='نوع')),
                ('is_primary', models.BooleanField(default=False, verbose_name='اصلی')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
                'ordering': ['-is_primary', 'label'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='پیش\u200cفرض ۶۰ روز از ایجاد', null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='request',
            name='source',
            field=models.CharField(choices=[('walk_in', 'مراجعه حضوری'), ('referral', 'معرفی'), ('portal', 'پورتال'), ('public_form', 'فرم عمومی'), ('social', 'شبکه اجتماعی'), ('direct', 'تماس مستقیم'), ('other', 'سایر')], default='walk_in', max_length=20, verbose_name='منبع مراجعه'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال پیگیری'), ('matched', 'تطبیق یافته'), ('closed', 'بسته شده'), ('cancelled', 'لغو شده'), ('expired', 'منقضی')], db_index=True, default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('contact_type', models.CharField(choices=[('owner', 'مالک'), ('buyer', 'مراجعه\u200cکننده / خریدار'), ('investor', 'سرمایه\u200cگذار'), ('colleague', 'همکار'), ('other', 'سایر')], db_index=True, default='buyer', max_length=20, verbose_name='نوع مخاطب')),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='شماره اصلی')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, help_text='برای جستجو و یکتایی — مقدار رمزنگاری\u200cنشده', max_length=15, verbose_name='شماره اصلی (نرمال\u200cشده)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='crm.contact', verbose_name='ادغام شده در')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('channel', models.CharField(default='sms', help_text='sms | whatsapp | ...', max_length=20, verbose_name='کانال')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان رضایت')),
                ('source', models.CharField(choices=[('in_person', 'حضوری'), ('public_form', 'فرم عمومی'), ('phone', 'تلفنی'), ('other', 'سایر')], default='in_person', max_length=20, verbose_name='منبع')),
                ('text_version', models.CharField(default='v1', max_length=20, verbose_name='نسخه متن رضایت')),
                ('consent_text', models.TextField(blank=True, verbose_name='متن رضایت نشان داده شده')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('revoke_reason', models.CharField(blank=True, max_length=300, verbose_name='دلیل لغو')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='agencies.agency', verbose_name='آژانس')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consents', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='crm.contact', verbose_name='مخاطب')),
            ],
            options={
                'verbose_name': 'رضایت پیامک',
                'verbose_name_plural': 'رضایت\u200cنامه\u200cها',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='crm.contact', verbose_name='مخاطب'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['contact'], name='crm_request_contact_e7b659_idx'),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='crm.contact', verbose_name='مخاطب'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['agency', 'contact_type'], name='crm_contact_agency__c0802a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['agency', 'phone_normalized'], name='crm_contact_agency__f9bb81_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['agency', 'contact', 'channel'], name='crm_consent_agency__1a75b3_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['contact', 'revoked_at'], name='crm_consent_contact_49d316_idx'),
        ),
    ]
