# Generated by Django 5.2 on 2026-09-23 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_invitation'),
        ('crm', '0003_contactphone_request_expires_at_alter_request_source_and_more'),
        ('listings', '0005_import_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('kind', models.CharField(choices=[('call', 'تماس'), ('sms', 'پیامک'), ('note', 'یادداشت'), ('status_change', 'تغییر وضعیت'), ('visit', 'بازدید'), ('other', 'سایر')], db_index=True, default='note', max_length=20, verbose_name='نوع رویداد')),
                ('summary', models.CharField(max_length=200, verbose_name='خلاصه')),
                ('detail', models.TextField(blank=True, verbose_name='جزئیات')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان رویداد')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact', verbose_name='مخاطب')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='listings.listing', verbose_name='فایل')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.request', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'تعامل',
                'verbose_name_plural': 'تایم\u200cلاین تعاملات',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['agency', 'occurred_at'], name='crm_interac_agency__da29e7_idx'), models.Index(fields=['agency', 'contact', 'occurred_at'], name='crm_interac_agency__1460cd_idx'), models.Index(fields=['agency', 'listing', 'occurred_at'], name='crm_interac_agency__460eef_idx'), models.Index(fields=['agency', 'request', 'occurred_at'], name='crm_interac_agency__d959bd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('contact__isnull', False), ('listing__isnull', False), ('request__isnull', False), _connector='OR'), name='interaction_has_at_least_one_target')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('kind', models.CharField(choices=[('info', 'اطلاع'), ('success', 'موفق'), ('warning', 'هشدار'), ('error', 'خطا')], default='info', max_length=10, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='لینک')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده\u200cشده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='crm_notific_user_id_3340ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='موعد انجام')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'بالا')], db_index=True, default='normal', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='یادآوری سررسید فقط یک\u200cبار ارسال می\u200cشود', null=True, verbose_name='آخرین یادآوری')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('related_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.contact', verbose_name='مخاطب مرتبط')),
                ('related_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='listings.listing', verbose_name='فایل مرتبط')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.request', verbose_name='درخواست مرتبط')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['assignee', 'status', 'due_at'], name='crm_task_assigne_835ba0_idx'), models.Index(fields=['agency', 'status', 'due_at'], name='crm_task_agency__c20fe9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='زمان قرار')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('status', models.CharField(choices=[('scheduled', 'قرار\u200cگذاشته'), ('completed', 'انجام\u200cشده'), ('cancelled', 'لغوشده'), ('no_show', 'حاضر نشد')], db_index=True, default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('outcome', models.CharField(blank=True, choices=[('interested', 'علاقه\u200cمند'), ('rejected', 'رد کرد'), ('thinking', 'در حال فکر کردن'), ('none', 'نامشخص')], default='none', max_length=20, verbose_name='نتیجه')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_visits', to=settings.AUTH_USER_MODEL, verbose_name='مشاور همراه')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.contact', verbose_name='مراجعه\u200cکننده')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='listings.listing', verbose_name='فایل')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='crm.request', verbose_name='درخواست مرتبط')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['agency', 'status', 'scheduled_at'], name='crm_visit_agency__11043e_idx'), models.Index(fields=['agency', 'contact', 'scheduled_at'], name='crm_visit_agency__79d79e_idx'), models.Index(fields=['listing', 'scheduled_at'], name='crm_visit_listing_566df0_idx')],
            },
        ),
    ]
