# Generated by Django 5.2 on 2026-09-20 21:35

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_agency_member'),
        ('listings', '0002_rename_listings_li_agency_status_idx_listings_li_agency__a8e908_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('portal', models.CharField(choices=[('dummy', 'پورتال آزمایشی (Dummy)'), ('divar', 'دیوار'), ('sheypoor', 'شیپور')], db_index=True, default='dummy', max_length=20, verbose_name='پورتال')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('credentials', apps.core.fields.EncryptedCharField(blank=True, max_length=2000, verbose_name='اطلاعات دسترسی (API key / token)')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='تنظیمات اختصاصی هر پورتال به صورت JSON', verbose_name='تنظیمات اضافه')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
            ],
            options={
                'verbose_name': 'تنظیمات پورتال',
                'verbose_name_plural': 'تنظیمات پورتال\u200cها',
                'ordering': ['portal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال ارسال'), ('success', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('external_id', models.CharField(blank=True, help_text='ID آگهی پس از انتشار موفق', max_length=200, verbose_name='شناسه در پورتال')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('retries', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_jobs', to='listings.listing', verbose_name='فایل ملک')),
                ('portal_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='publishing.portalconfig', verbose_name='تنظیمات پورتال')),
            ],
            options={
                'verbose_name': 'کار انتشار',
                'verbose_name_plural': 'کارهای انتشار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portalconfig',
            index=models.Index(fields=['agency', 'portal', 'is_active'], name='publishing__agency__78b12e_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('agency', 'portal'), name='unique_active_portal_per_agency'),
        ),
        migrations.AddIndex(
            model_name='publishjob',
            index=models.Index(fields=['agency', 'status'], name='publishing__agency__edeef8_idx'),
        ),
        migrations.AddIndex(
            model_name='publishjob',
            index=models.Index(fields=['agency', 'listing'], name='publishing__agency__929a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='publishjob',
            index=models.Index(fields=['listing', 'portal_config'], name='publishing__listing_836d78_idx'),
        ),
    ]
