# Generated by Django 5.2 on 2026-09-24 18:38

import apps.ai.models
import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_invitation'),
        ('listings', '0005_import_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (Whisper)'), ('gemini', 'گوگل Gemini'), ('console', 'کنسول (توسعه)')], default='console', max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('api_key', apps.core.fields.EncryptedCharField(blank=True, help_text='رمزنگاری\u200cشده در پایگاه داده', verbose_name='کلید API')),
                ('model_name', models.CharField(blank=True, help_text='مثلاً whisper-1 یا gemini-2.0-flash — خالی = پیش\u200cفرض ارائه\u200cدهنده', max_length=100, verbose_name='نام مدل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
            ],
            options={
                'verbose_name': 'تنظیمات هوش مصنوعی آژانس',
                'verbose_name_plural': 'تنظیمات هوش مصنوعی آژانس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('audio', models.FileField(max_length=500, upload_to=apps.ai.models._voice_upload_path, verbose_name='فایل صوتی')),
                ('original_filename', models.CharField(blank=True, max_length=300, verbose_name='نام فایل اصلی')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت (ثانیه)')),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='زبان')),
                ('status', models.CharField(choices=[('uploaded', 'آپلودشده'), ('queued', 'صف رونویسی'), ('transcribing', 'در حال رونویسی'), ('transcribed', 'رونویسی\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='uploaded', max_length=20, verbose_name='وضعیت')),
                ('transcript', models.TextField(blank=True, verbose_name='متن رونویسی')),
                ('provider', models.CharField(blank=True, choices=[('openai', 'OpenAI (Whisper)'), ('gemini', 'گوگل Gemini'), ('console', 'کنسول (توسعه)')], max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('provider_file_id', models.CharField(blank=True, max_length=200, verbose_name='شناسه نزد ارائه\u200cدهنده')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='پیغام خطا')),
                ('transcribed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رونویسی')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_notes', to='listings.listing', verbose_name='فایل ملک')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_voice_notes', to=settings.AUTH_USER_MODEL, verbose_name='آپلود توسط')),
            ],
            options={
                'verbose_name': 'یادداشت صوتی',
                'verbose_name_plural': 'یادداشت\u200cهای صوتی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('data', models.JSONField(default=dict, verbose_name='داده استخراج\u200cشده')),
                ('missing', models.JSONField(default=list, verbose_name='فیلدهای ناموجود')),
                ('confidence', models.FloatField(default=0.0, verbose_name='اطمینان')),
                ('parser', models.CharField(blank=True, max_length=20, verbose_name='پارسر')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('applied', 'به فایل اعمال\u200cشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='agencies.agency', verbose_name='آژانس')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_drafts', to='listings.listing', verbose_name='فایل ساخته\u200cشده')),
                ('voice_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='ai.voicenote', verbose_name='یادداشت صوتی')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس صوتی',
                'verbose_name_plural': 'پیش\u200cنویس\u200cهای صوتی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voicenote',
            index=models.Index(fields=['agency', 'status'], name='ai_voicenot_agency__d508a2_idx'),
        ),
        migrations.AddIndex(
            model_name='voicenote',
            index=models.Index(fields=['agency', 'created_at'], name='ai_voicenot_agency__8a1bc1_idx'),
        ),
    ]
