"""
Agencies app models: Agency, Branch, AgencyMember, Invitation.
"""

import secrets
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.core.models import TimeStampedModel

# ─── Optional PostGIS support ─────────────────────────────────────────────────
try:
    from django.contrib.gis.db import models as gis_models

    _HAS_GIS = True
except Exception:  # noqa: BLE001
    gis_models = None  # type: ignore[assignment]
    _HAS_GIS = False


class AgencyPlan(models.TextChoices):
    FREE = "free", _("رایگان")
    PRO = "pro", _("حرفه‌ای")
    ENTERPRISE = "enterprise", _("سازمانی")


class Agency(TimeStampedModel):
    """Top-level tenant. Each agency is an independent real-estate office."""

    name = models.CharField(_("نام"), max_length=200)
    slug = models.SlugField(_("اسلاگ"), unique=True, max_length=80, allow_unicode=False)
    logo = models.ImageField(_("لوگو"), upload_to="agencies/logos/", blank=True, null=True)
    phone = models.CharField(_("تلفن"), max_length=20, blank=True)
    address = models.TextField(_("آدرس"), blank=True)
    plan = models.CharField(
        _("پلن"),
        max_length=20,
        choices=AgencyPlan.choices,
        default=AgencyPlan.FREE,
    )
    is_active = models.BooleanField(_("فعال"), default=True)

    class Meta:
        verbose_name = _("آژانس")
        verbose_name_plural = _("آژانس‌ها")
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Branch(TimeStampedModel):
    """A physical branch of an Agency."""

    agency = models.ForeignKey(
        Agency,
        on_delete=models.CASCADE,
        related_name="branches",
        verbose_name=_("آژانس"),
    )
    name = models.CharField(_("نام شعبه"), max_length=200)
    address = models.TextField(_("آدرس"), blank=True)
    location = (
        gis_models.PointField(_("موقعیت جغرافیایی"), geography=True, blank=True, null=True)
        if _HAS_GIS
        else models.TextField(_("موقعیت جغرافیایی (WKT)"), blank=True)
    )
    phone = models.CharField(_("تلفن"), max_length=20, blank=True)
    is_active = models.BooleanField(_("فعال"), default=True)

    class Meta:
        verbose_name = _("شعبه")
        verbose_name_plural = _("شعبه‌ها")
        ordering = ["agency", "name"]

    def __str__(self) -> str:
        return f"{self.agency.name} — {self.name}"


class AgencyMemberRole(models.TextChoices):
    OWNER = "owner", _("مالک")
    AGENT = "agent", _("مشاور")
    VIEWER = "viewer", _("مشاهده‌گر")


class AgencyMember(TimeStampedModel):
    """Junction table linking a CustomUser to an Agency with a role."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="agency_memberships",
        verbose_name=_("کاربر"),
    )
    agency = models.ForeignKey(
        Agency,
        on_delete=models.CASCADE,
        related_name="members",
        verbose_name=_("آژانس"),
    )
    role = models.CharField(
        _("نقش"),
        max_length=20,
        choices=AgencyMemberRole.choices,
        default=AgencyMemberRole.AGENT,
    )
    joined_at = models.DateTimeField(_("تاریخ عضویت"), auto_now_add=True)

    class Meta:
        verbose_name = _("عضو آژانس")
        verbose_name_plural = _("اعضای آژانس")
        unique_together = [("user", "agency")]

    def __str__(self) -> str:
        return f"{self.user} @ {self.agency.name} ({self.role})"


# ─── Invitation ───────────────────────────────────────────────────────────────

_INVITE_TTL_HOURS = 48


class Invitation(TimeStampedModel):
    """
    Single-use invitation link for joining an agency.

    Generated by an owner; consumed when the invitee logs in via OTP.
    Expires after _INVITE_TTL_HOURS hours.
    """

    agency = models.ForeignKey(
        Agency,
        on_delete=models.CASCADE,
        related_name="invitations",
        verbose_name=_("آژانس"),
    )
    invited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="sent_invitations",
        verbose_name=_("دعوت‌کننده"),
    )
    phone = models.CharField(
        _("شماره موبایل مدعو"),
        max_length=15,
        blank=True,
        help_text=_("اگر مشخص باشد — وگرنه هر کاربری با لینک می‌تواند استفاده کند"),
    )
    role = models.CharField(
        _("نقش پیشنهادی"),
        max_length=20,
        choices=AgencyMemberRole.choices,
        default=AgencyMemberRole.AGENT,
    )
    token = models.CharField(
        _("توکن"),
        max_length=64,
        unique=True,
        editable=False,
    )
    is_used = models.BooleanField(_("استفاده شده"), default=False)
    used_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="accepted_invitations",
        verbose_name=_("استفاده‌کننده"),
    )
    used_at = models.DateTimeField(_("زمان استفاده"), null=True, blank=True)
    expires_at = models.DateTimeField(_("انقضا"), db_index=True)

    class Meta:
        verbose_name = _("دعوت‌نامه")
        verbose_name_plural = _("دعوت‌نامه‌ها")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["agency", "is_used"]),
        ]

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = secrets.token_urlsafe(48)
        if not self.expires_at:
            self.expires_at = timezone.now() + timedelta(hours=_INVITE_TTL_HOURS)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        target = self.phone or "هر کسی"
        return f"دعوت‌نامه {self.agency.name} → {target} ({self.role})"

    @property
    def is_valid(self) -> bool:
        """True if the invitation can still be used."""
        return not self.is_used and timezone.now() < self.expires_at

    def accept(self, user) -> "AgencyMember":
        """
        Mark invitation as used and create/update AgencyMember.
        Call inside a transaction.
        """
        member, _ = AgencyMember.objects.get_or_create(
            user=user,
            agency=self.agency,
            defaults={"role": self.role},
        )
        self.is_used = True
        self.used_by = user
        self.used_at = timezone.now()
        self.save(update_fields=["is_used", "used_by", "used_at"])
        return member
